# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend"

# NOTE
# we set priority higher than the STM layer
BBFILE_COLLECTIONS += "thornxt"
BBFILE_PATTERN_thornxt = "^${LAYERDIR}/"
BBFILE_PRIORITY_thornxt = "10"

LAYERSERIES_COMPAT_thornxt = "scarthgap"
LAYERVERSION_thornxt = "1"

# Remove unwanted features from the ST layer.
MACHINE_FEATURES:remove = "bluetooth wifi fw-update"
DISTRO_FEATURES:remove = "zeroconf ofono bluetooth 3g nfc"

# Remove unwanted dependencies from the ST layer.
LAYERDEPENDS_st-openstlinux:remove = "webserver gnome-layer multimedia-layer"

# Mask out unwanted recipes folders.
BBMASK += "/meta-st-openstlinux/recipes-multimedia/gstreamer/"
BBMASK += "/meta-st-openstlinux/recipes-webadmin/"
BBMASK += "/meta-st-openstlinux/recipes-samples/"
BBMASK += "/meta-st-openstlinux/oe-core/recipes-gnome/"
BBMASK += "/meta-st-openstlinux/oe-core/recipes-core/systemd/"

# Mask out unwanted recipes files.
BBMASK += "meta-st-openstlinux/recipes-multimedia/libcamera/libcamera-stm32mp_%.bb"

EULA_FILE_ST:stm32mpcommon = "${LAYERDIR}/conf/eula/${MACHINE}"
EULA_FILE_ST_MD5SUM:stm32mpcommon = "CAB068EAC2EC7EFE0FE07A3260C0194B"

# OpenSTLinux compatibility version
#ST_OSTL_COMPATIBILITY_VERSION_thornxt = "6.2"
